#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "50x"
# logo text will only show when logo is missing.
logo_text = "Unive One"
# OpenGraph / Twitter Card metadata
description = "SAAS"
author = "Unive One"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Future of School Management"

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "@2022 Unive One, All Rights Reserved."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "Level 4, Vision 2021 Tower, Kawran Bazar, Dhaka-1215"
phone = ["+880-1881997646", "+880-1689543959"]
email = ["contact@unive.one"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Try Demo"
link = "https://unive.one/contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Get Unive One Now"
content = "Automate your instituition's workflow"
button = "Try a Demo"
button_link = "https://unive.one/contact"

############################# social site ########################
[[social]]
title = "Unive One"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://facebook.com/unive.one"

[[social]]
title = "Unive One"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "Unive One"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

#[[social]]
#title = "AndromedaPin"
#icon = "lab la-pinterest" # https://icons8.com/line-awesome
#link = "#!"
